export const SCIENCE_STORIES = [
  {
    id: 'arabian-sea-monsoon',
    title: 'Arabian Sea Monsoon Currents & Coastal Upwelling',
    region: 'Arabian Sea / West Coast of India',
    badge: 'Ocean Dynamics',
    summary: 'Discover how the Southwest Monsoon reverses the Somali and West India coastal currents, driving nutrient-rich cold upwelling water to the surface and boosting marine fisheries.',
    steps: [
      {
        title: '1. Summer Pre-Monsoon Surface Heating',
        narration: 'Intense solar radiation creates sea surface temperatures exceeding 30°C in the northern Arabian Sea before the summer monsoon onset.',
        variable: 'temp',
        palette: 'thermal',
        exaggeration: 30,
        isIsosurface: false,
        camera: { pos: [0, 160, 240], target: [0, -20, 0] },
      },
      {
        title: '2. Coastal Upwelling & Thermocline Shoaling',
        narration: 'Alongshore monsoon winds push surface water offshore (Ekman transport), lifting cold 18°C thermocline water upward along the coast of Kerala and Goa.',
        variable: 'temp',
        palette: 'thermal',
        exaggeration: 45,
        isIsosurface: true,
        isovalue: 0.55,
        camera: { pos: [-70, 70, 110], target: [-30, -15, 0] },
      },
      {
        title: '3. Biological Productivity Explosion (Chlorophyll-a)',
        narration: 'The upwelled nutrients trigger massive phytoplankton blooms along the southwest coast of India, creating the richest fishing grounds in the subcontinent.',
        variable: 'chlorophyll',
        palette: 'chlorophyll',
        exaggeration: 35,
        isIsosurface: false,
        camera: { pos: [-50, 90, 130], target: [-20, -10, 0] },
      },
    ],
  },
  {
    id: 'bay-of-bengal-salinity',
    title: 'Bay of Bengal Freshwater Barrier Layer',
    region: 'Bay of Bengal / East Coast of India',
    badge: 'Salinity & Cyclones',
    summary: 'Massive monsoon river discharge (Ganges, Brahmaputra, Godavari) creates a thin, low-salinity surface lens that inhibits vertical mixing and fuels intense tropical cyclone intensification.',
    steps: [
      {
        title: '1. Low-Salinity Surface Plume',
        narration: 'Monsoon river runoff lowers surface salinity below 32 PSU in the northern Bay of Bengal, creating an intense vertical salinity gradient (halocline).',
        variable: 'salt',
        palette: 'haline',
        exaggeration: 30,
        isIsosurface: false,
        camera: { pos: [80, 140, 160], target: [45, -15, 0] },
      },
      {
        title: '2. Thermal Inversion & Barrier Layer Formation',
        narration: 'The strong salinity stratification prevents cold deeper water from mixing upward, trapping heat in a "barrier layer" that rapidly intensifies passing tropical cyclones.',
        variable: 'salt',
        palette: 'haline',
        exaggeration: 50,
        isIsosurface: true,
        isovalue: 0.35,
        camera: { pos: [60, 60, 90], target: [40, -15, 0] },
      },
    ],
  },
  {
    id: 'in-situ-fleet-synergy',
    title: 'Autonomous In-Situ Fleet: Argo Floats & Ocean Gliders',
    region: 'Indian Ocean Basin-Wide Network',
    badge: 'Observational Tech',
    summary: 'Observe how INCOIS deploys autonomous robotic Argo profiling floats and underwater gliders that dive to 2000m depth, sending real-time CTD data to continuously calibrate numerical models.',
    steps: [
      {
        title: '1. 2000-Meter Deep Argo Profiling Cycle',
        narration: 'Argo floats drift at 1000m depth for 10 days before descending to 2000m and ascending to the surface, measuring temperature and salinity profiles validated against numerical simulations.',
        variable: 'temp',
        palette: 'thermal',
        exaggeration: 35,
        isIsosurface: false,
        camera: { pos: [30, 110, 190], target: [10, -20, 0] },
      },
      {
        title: '2. Autonomous Glider High-Resolution Sawtooth Dives',
        narration: 'Underwater gliders use buoyancy engines to perform yo-yo sawtooth dives, capturing fine-scale ocean eddies and thermocline undulations along critical shipping lanes.',
        variable: 'temp',
        palette: 'thermal',
        exaggeration: 45,
        isIsosurface: false,
        camera: { pos: [70, 70, 100], target: [50, -20, 0] },
      },
    ],
  },
];
